name: SonarQube Desktop-only

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-and-analyze-desktop:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      # --- Create a CI-only settings file that excludes Android (and any other mobile modules) ---
      # Adjust the includes to match your actual desktop modules.
      - name: Create desktop-only settings
        run: |
          cat > settings-ci.gradle.kts <<'EOF'
          rootProject.name = "libgdx-desktop-ci"
          // Include ONLY desktop-related subprojects here:
          include(":core", ":desktop")
          // If you have more non-Android modules, add them:
          // include(":shared", ":tools", ":lwjgl3", ":headless")
          EOF

      - name: Make Gradle executable
        run: chmod +x gradlew

      # Build only the projects listed in settings-ci.gradle.kts
      - name: Build desktop
        run: ./gradlew -c settings-ci.gradle.kts build --warning-mode all --info

      # Run SonarQube analysis on just those modules
      - name: SonarQube analyze (desktop-only)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # If using a self-hosted SonarQube, also set SONAR_HOST_URL secret:
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradlew -c settings-ci.gradle.kts sonar \
            -Dsonar.login=${SONAR_TOKEN} \
            ${{ secrets.SONAR_HOST_URL && format('-Dsonar.host.url={0}', secrets.SONAR_HOST_URL) || '' }}
