name: SonarQube Desktop-only

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-and-analyze-desktop:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      # --- Desktop-only settings (adjust includes as needed) ---
      - name: Create desktop-only settings
        run: |
          cat > settings-ci.gradle.kts <<'EOF'
          // Only include desktop-friendly modules here.
          rootProject.name = "libgdx-desktop-ci"
          include(":gdx")
          include(":backends:gdx-backend-lwjgl3")
          // If you need extras (e.g., tools), add more here:
          // include(":extensions:gdx-tools")
          EOF

      # --- Band-aid: comment out any references to the Android tests project ---
      - name: Disable android tests references
        run: |
          if grep -RIn ":tests:gdx-tests-android" build.gradle; then
            sed -E -i 's/(.*:tests:gdx-tests-android.*)/\/\/ \1/g' build.gradle
          fi

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build desktop
        run: ./gradlew -c settings-ci.gradle.kts build --warning-mode all --info

      - name: SonarQube analyze (desktop-only)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # For self-hosted SonarQube add a repo secret SONAR_HOST_URL and it will be used:
          # SONAR_HOST_URL: https://sonar.yourcompany.tld
        run: |
          ./gradlew -c settings-ci.gradle.kts sonar \
            -Dsonar.login=${SONAR_TOKEN} \
            ${{ secrets.SONAR_HOST_URL && format('-Dsonar.host.url={0}', secrets.SONAR_HOST_URL) || '' }}
