name: build-and-sonar

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Android SDK components
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install build tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-35" "build-tools;34.0.0" # match your AGP expectations

      - name: Gradle wrapper permissions
        run: chmod +x gradlew

      # Build everything first (scanner doesn't auto-hook compile since 5.0)
      - name: Build
        run: ./gradlew build --warning-mode all

      - name: SonarQube / SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar -Dsonar.login=${SONAR_TOKEN}
